language: node_js

node_js:
  - '8.11.4'

cache:
  "yarn": true
  "directories":
    - '.eslintcache'
    - 'node_modules'

install:
  - yarn install

before_script:
  - npm run start-server-dev

script:
  - yarn test

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
